name: ExtraSpawners
version: ${project.version}
main: me.derpy.extraspawners.Main
api-version: 1.17
authors: [derpy588]
description: ExtraSpawners will add so much to spawners. It's a all in one spawner plugin.
